
name: build-and-publish

run-name: ${{ github.ref_name }}-${{ github.run_number }}

on:
  push:
    branches:
      - '*'

jobs:
  docker-build-image:
    concurrency:
      group: docker-build-image-${{ github.ref_name }}
    runs-on: 'ubuntu-22.04'
    steps:
      - name: Checkout Artifactory
        uses: actions/checkout@v3
 
      - name: Build Docker Image
        run: |
          docker build --force-rm=true -t github-${{ github.ref_name }}-${{ github.run_number }} .
          docker images
        
                
      
    
