name: eventstore-deployment

on:
  workflow_dispatch:
    inputs:
      environment_group:
        description: 'Select the environment group to deploy'
        required: true
        type: choice
        options:
          - eventstore
          - redis

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set environment list
        id: set_envs
        run: |
          if [[ "${{ github.event.inputs.environment_group }}" == "eventstore" ]]; then
            echo "ENVIRONMENTS=eventstore/eu1-Es-Enterprise-Tesseract-2 eventstore/eu1-Es-Swiggy-Tesseract-1 eventstore/eu1-Es-Enterprise-Tesseract-2" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment_group }}" == "redis" ]]; then
            echo "ENVIRONMENTS=logprocessor/eu1-Logprocessor-Enterprise-Tesseract-1 logprocessor/eu1-Logprocessor-Enterprise-Tesseract-2" >> $GITHUB_ENV
          fi

      - name: Deploy to environments
        run: |
          for env in ${{ env.ENVIRONMENTS }}; do
            echo "Deploying to $env"
            # Add your deployment script or steps here
          done
