name: eventstore-deploy
run-name: ${{ github.ref_name }}-on-${{ inputs.stackname }}
on:
  workflow_dispatch:
    inputs:
      stackname:
        description: Select stack for a deployment
        type: choice
        options: 
          - ${{ vars.EVENTSTORE }}
        

jobs:
  eventstore-release:
    concurrency: release
    runs-on: 'ubuntu-latest'
    environment: ${{ inputs.stackname }}
    if: github.run_attempt == 1
    steps:

      - name: Unzip Asset
        run: echo ${{ github.ref }}
