
name: build-and-publish

run-name: ${{ github.ref_name }}-${{ github.run_number }}

on:
  workflow_dispatch:

jobs:
  docker-build-image:
    concurrency:
      group: docker-build-image-${{ github.ref_name }}
    runs-on: 'ubuntu-22.04'
    permissions:
      contents: write
    steps:
      - name: Checkout Artifactory
        uses: actions/checkout@v3
 
      - name: Build Docker Image
        run: |
          docker build --force-rm=true -t github-${{ github.ref_name }}-${{ github.run_number }} .
          docker images
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: eventstore-${{ github.ref_name }}-${{ github.run_number }}
          release_name: eventstore-${{ github.ref_name }}-${{ github.run_number }}
          draft: false
          prerelease: false
        
                
      
    
