name: eventstore
run-name: ${{ github.ref_name }}-on-${{ inputs.stackname }}
on:
  workflow_dispatch:
    inputs:
      stackname:
        description: Select stack for a deployment
        type: choice
        options:
          - eu1-Es-Enterprise-Tesseract-1
          - eu1-Es-Enterprise-Tesseract-2

jobs:
  eventstore-release:
    concurrency: release
    runs-on: 'ubuntu-latest'
    environment: eventstore/${{ inputs.stackname }}
    if: github.run_attempt == 1
    steps:

      - name: Unzip Asset
        run: echo ${{ github.ref }}
